logging.level:
  org.springframework: INFO

server:
  error:
    includeStacktrace: ALWAYS

spring.cloud.gateway.routes:
  - uri: http://localhost:8000
    predicates:
      - App=/manager
    filters:
      - Auth
      - RewritePath=/manager(?<segment>/?.*),$\{segment}
  - uri: http://localhost:8084
    predicates:
      - Svc=/svc,manager
    filters:
      - ApiAuth
      - RewritePath=/svc(?<segment>/?.*),$\{segment}
  - uri: http://localhost:8085
    predicates:
      - Svc=${yada.contextPath}/svc,user
    filters:
      - ApiAuth
      - RewritePath=/svc(?<segment>/?.*),$\{segment}

management.endpoints:
  web.exposure.include: metrics,gateway
  health.show-details: always
#yada.db.mongo.uri: 'mongodb://localhost/yada_auth?replicaSet=rs'
