logging:
  level:
    root: info
    org.springframework.security: trace
server:
  port: 9000
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/sspManager
        registration:
          keycloak:
            client-id: gateway
            client-secret: ee861007-3394-4a79-9d6c-9ca3ebd2e738
            scope:
             - openid
  cloud:
    gateway:
      routes:
        - id: ssp-service
          uri: http://localhost:9001
          predicates:
            - Path=/svc/ssp/**
          filters:
            - OAuthApi
            - RewritePath=/svc(?<segment>/?.*),$\{segment}
            - RemoveRequestHeader=Cookie
        - id: web-service
          uri: http://localhost:9002
          predicates:
            - Path=/svc/web/**
          filters:
            - OAuthApi
            - RewritePath=/svc/web(?<segment>/?.*),$\{segment}
            - RemoveRequestHeader=Cookie
        - id: changePwd
          uri: http://localhost:8180
          predicates:
            - Path=/changePwd
          filters:
            - RedirectTo=302, http://localhost:8180/auth/realms/sspManager/account/password
        - id: app
          uri: http://localhost:9000
          predicates:
            - Path=/**
          filters:
            - name: OAuth
              args:
                staticPaths: /**.js,/**.css
            - StaticRes
  web:
    resources:
      static-locations: classpath:/static/, file:/Users/lirenhao/Workspace/ssp/SspManger/app/dist