logging.level:
  org.springframework: INFO

server:
  error:
    includeStacktrace: ALWAYS

spring.thymeleaf.cache: false

spring.cloud.gateway.routes:
  - uri: http://localhost:8000
    predicates:
      - Path=/dev-server/**
  - uri: http://localhost:8000
    predicates:
      - App=/ssp
    filters:
      - Auth
      - RewritePath=/ssp(?<segment>/?.*),$\{segment}
  - uri: http://localhost:8084
    predicates:
      - Svc=/svc,info
    filters:
      - ApiAuth
      - RewritePath=/svc(?<segment>/?.*),$\{segment}
  - uri: http://localhost:8085
    predicates:
      - Svc=/svc,web
    filters:
      - ApiAuth
      - RewritePath=/svc(?<segment>/?.*),$\{segment}
  - uri: http://localhost:8000
    predicates:
      - Path=/svc/**

management.endpoints:
  web.exposure.include: metrics,gateway
  health.show-details: always

jwt.secret: yadajwt

yada:
  recaptcha:
    type: None
  security:
    defaultPwd: 111111
#yada.db.mongo.uri: 'mongodb://localhost/yada_auth?replicaSet=rs'
